package-lock.json, package.json, script/seed.js, server/db/models/category.js, server/db/models/index.js, server/db/models/legging.js
=> Feature: created database and models

script/seed.js, server/api/index.js, server/api/leggings.js, server/api/products.js, server/db/models/bra.js, server/db/models/index.js
---
I feel like I might have violated our norm.
I created a new bra model based on the Legging model to test the eager loading. I have one commit on creating the model and one commit on fixing the eager loading. I hope I am not overstepping on Rachel's work.
=> Api route #5

client/components/all-products.js, client/components/product.js, public/style.css
=> Components #6

client/components/all-products.js, client/components/index.js, client/routes.js, client/store/product.js
=> Fixed: all products displaying again

server/api/products.spec.js
=> Adding backend route tests to master

public/style.css, server/api/users.js
=> Feature: routers for users and user

server/api/products.spec.js, server/api/users.spec.js
Added specs for the api/user routes
=> Post specs #16

public/index.html
=> Fixed: title of webpage from Boilermaker to LaLaLime

server/db/models/order.js, server/db/models/product.js
=> Feature: created order model

client/components/all-products.js, client/components/product.js, client/components/single-product.js, client/routes.js, client/store/product.js, server/api/products.js
=> Fixed singleProduct view

client/components/single-product.js, client/store/user.js, server/api/products.js, server/api/users.js
=> Single product connectivity

client/store/cart.js
=> Fixed: changed api route from leggings to products

client/components/single-product.js, client/components/user-home.js, client/store/cart.js, client/store/user.js
=> Fixed: refactored user reducer and migrated to cart reducer

client/components/single-product.js, client/store/cart.js, client/store/index.js, client/store/product.js, script/seed.js, server/api/cart.js, server/api/index.js, server/api/users.js, server/db/models/index.js, server/db/models/order.js, server/db/models/productOrder.js
---
This is a combination pull request of 'adding to cart' and 'add another column in the through table'
=> Add column #37

client/components/cart-item.js, client/components/cart.js, client/components/navbar.js, client/store/cart.js, client/store/product.js, server/api/cart.js
=> Cart slice #12

client/components/navbar.js, client/routes.js
=> fix guest view

client/components/cart-item.js, client/components/cart.js, client/components/checkout.js, client/components/index.js, client/routes.js, client/store/checkout.js, client/store/index.js, public/style.css
---
- Edited cart CSS
- Added Order Summary section to cart page with checkout button
- Added checkout component with a form and added a reducer file (depending on if we need it)
=> Checkout #14

client/store/cart.js, client/store/user.js, server/api/cart.js
=> fix cart increment and decrement instant view update

client/components/cart.js, client/store/cart.js, server/api/cart.js
=> Fix cartfunction

client/components/cart.js, client/store/cart.js, script/seed.js, server/api/cart.js, server/index.js
Changed the condition in cart component to check for type of cartItem entries, since it will be an array now even if the cart is empty and/or forbidden
=> Updating privacy to align with new api route

client/components/cart.js, client/store/cart.js, server/api/cart.js, server/auth/index.js, server/index.js
=> fix cart view and guess user sign up experience

client/components/single-product.js, client/store/cart.js, public/style.css, server/api/cart.js, server/db/models/product.js
=> Single view ui #55

server/api/users.spec.js, server/auth/index.js, server/db/models/product.js, server/db/models/productOrders.spec.js
=> Fix api/user.spec

server/api/products.spec.js, server/db/models/product.spec.js
---
- product attribute: trying to add in "can handle long description" but validation is throwing back error on product.category being null when it's not. 
- trying to create an instance of the product and save() but unable to. Any suggestions would be appreciated!
=> Product tests

server/api/cart.spec.js, server/db/models/order.js, server/db/models/order.spec.js, server/db/models/product.spec.js, server/db/models/productOrders.spec.js
---
We're still not passing the ProductOrder and User-Home tests. The error I'm getting is "SequelizeForeignKeyConstraintError", which can be fixed by adding {constraints: false} to the association. However, this prevents the foreign key relationship inside the tables where the constraints have been set to false.
=> Ordermodeltest

client/app.js, client/components/cart.js, client/components/user-home.js, client/routes.js, client/store/cart.js, package-lock.json, public/style.css, server/api/cart.js
=> Refactor thunks #12

client/components/checkout.js, client/components/order-item.js, server/api/cart.js, server/index.js
=> Checkout #62

client/components/cart-item.js, client/components/recent-item.js
=> Fixed: changed href to link in cartitems and order items

client/components/home.js
=> Fixed home component

client/components/cart-item.js, client/components/cart.js, client/components/checkout.js, client/components/order-item.js, public/style.css, script/seed.js
=> Updated CSS

client/components/checkout.js, client/components/completed-order.js, client/components/navbar.js, client/routes.js, client/store/cart.js, public/style.css, server/api/order.js
=> Final touches

client/components/cart.js, client/components/completed-order.js, client/store/cart.js, client/store/user.js, package-lock.json, public/style.css, server/auth/google.js
=> Fixed: space in subtotal in cart view, sign up redirect goes to /profile

client/components/recent-item.js, client/components/user-home.js, public/style.css
=> Fixed: css in order page

README.md
=> Cerclecheung patch 1
